# Generated by Django 4.1.7 on 2023-03-01 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=30, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/images"
                    ),
                ),
                ("buyed_at", models.DateField(default=datetime.date(2023, 3, 1))),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guarantee_end", models.DateField(default=datetime.date(2025, 3, 1))),
                (
                    "proof_of_purchase",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/purchase"
                    ),
                ),
                (
                    "manual",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/manuals"
                    ),
                ),
            ],
        ),
    ]
